### ISSUE TITLE
Add WhatsApp to "Tech-Unternehmen"

### ISSUE THREAD

**Issue by someeuropeandude** [jfilter/youdata-data#3]
Adresse:
WhatsApp Ireland Limited
4 Grand Canal Square
Grand Canal Harbour
Dublin 2
Ireland

E-Mail-Adresse:
privacy.eu@support.whatsapp.com

Fax:
+1 (650) 543-7457

Source: https://www.whatsapp.com/contact/

**Comment by jfilter** [comment]
added, thanks!
